[versions]
applicationID = "com.example.vivchar.example"

minSdkVersion = "21"
targetSdkVersion = "34"
compileSdkVersion = "34"

retrofit = "2.11.0"

glide = "4.16.0"
glide-transformations = "4.3.0"

rxjava = "3.1.5"
rxkotlin = "3.0.1"
rxandroid = "3.0.2"

core-ktx = "1.13.1"
annotation = "1.8.0"
recyclerview = "1.3.2"
constraintlayout = "2.1.4"
coordinatorlayout = "1.2.0"
swiperefreshlayout = "1.1.0"
cardview = "1.0.0"
material = "1.12.0"
appcompat = "1.7.0"

plugin-application = "8.5.1"
plugin-library = "8.5.1"
plugin-kotlin = "1.9.0"
plugin-nexus = "2.0.0"
plugin-maven-publish = "0.36.0"

lifecycle = "2.8.3"
navigation = "2.7.7"
coroutines = "1.8.1"

kotlinVersion = "1.9.24"

[libraries]
rx-java = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rxjava" }
rx-kotlin = { group = "io.reactivex.rxjava3", name = "rxkotlin", version.ref = "rxkotlin" }
rx-android = { group = "io.reactivex.rxjava3", name = "rxandroid", version.ref = "rxandroid" }

androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
androidx-coordinatorlayout = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "coordinatorlayout" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "material" }

squareup-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
squareup-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }

kotlin-stdlib-jdk7 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk7", version.ref = "kotlinVersion" }

androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }

glide-core = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
glide-transformations = { group = "jp.wasabeef", name = "glide-transformations", version.ref = "glide-transformations" }

androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-rx3 = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-rx3", version.ref = "coroutines" }

[plugins]
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "plugin-kotlin" }
android-application = { id = "com.android.application", version.ref = "plugin-application" }
android-library = { id = "com.android.library", version.ref = "plugin-library" }
nexus-plugin = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "plugin-nexus" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "plugin-maven-publish" }